version: 1.0.{build}

image:
  # Ubuntu2204 needed for .NET 8 for now (see https://www.appveyor.com/docs/linux-images-software/)
  - Ubuntu2204
  - Visual Studio 2022

build_script:
  - dotnet build src/DistributedLock.sln -c Release
  
test_script:
  - dotnet test src/DistributedLock.sln -c Release -f net8.0 --no-build --filter TestCategory=CI

for: 
  - 
    matrix: 
      only: 
        - 
          image: "Visual Studio 2022"
    test_script:
      - dotnet test src/DistributedLock.sln -c Release --no-build --filter "TestCategory=CI|TestCategory=CIWindows"