version: 1.0.{build}

image: 
  - Visual Studio 2022
  - Ubuntu2204
  
build_script:
  - dotnet build src/DistributedLock.sln -c Release
  
test_script:
  - dotnet test src/DistributedLock.sln -c Release -f netcoreapp3.1 --no-build --filter TestCategory=CI

for: 
  - 
    matrix: 
      only: 
        - 
          image: "Visual Studio 2022"
    test_script:
      - dotnet test src/DistributedLock.sln -c Release --no-build --filter "TestCategory=CI|TestCategory=CIWindows"