version: 1.0.{build}

image: 
  - Visual Studio 2022
  - Ubuntu

init:
  - sh: sudo apt-get install -y gpg && wget -O - https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o microsoft.asc.gpg && sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/ && wget https://packages.microsoft.com/config/ubuntu/{os-version}/prod.list && sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list && sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg && sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list && sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0

build_script:
  - dotnet build src/DistributedLock.sln -c Release
  
test_script:
  - dotnet test src/DistributedLock.sln -c Release -f netcoreapp3.1 --no-build --filter TestCategory=CI

for: 
  - 
    matrix: 
      only: 
        - 
          image: "Visual Studio 2022"
    test_script:
      - dotnet test src/DistributedLock.sln -c Release --no-build --filter "TestCategory=CI|TestCategory=CIWindows"